### ISSUE TITLE
How to update the bUrp suite 

### ISSUE THREAD

**Issue by KaniskarK** [xiv3r/Burpsuite-Professional#14]
Now the Burp Pro Version is 2024.10.3 but the installed version 
![image](https://github.com/user-attachments/assets/b62a28fb-6aaf-4664-b3d0-697b831a8210)
 
 
 so how to upgarde to this version .

**Comment by xiv3r** [comment]
> Now the Burp Pro Version is 2024.10.3 but the installed version ![image](https://private-user-images.githubusercontent.com/76870433/391316007-b62a28fb-6aaf-4664-b3d0-697b831a8210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTQzMDQsIm5iZiI6MTczMzA1NDAwNCwicGF0aCI6Ii83Njg3MDQzMy8zOTEzMTYwMDctYjYyYTI4ZmItNmFhZi00NjY0LWIzZDAtNjk3YjgzMWE4MjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDExNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZTRmYmM3NmJiMTBhZmE2OWIzMzEyNjJiZDljYTM1ODZhMjgyYTYyZGFkODg0ZDE1NzZiY2NhNDViYWNjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1luXPXyXzFLoFIs7Zn5SGrh79EMyKb5tdpO3DEqlzp8)
> 
> so how to upgarde to this version .

Burpsuite license version is always behind the current latest version of burpsuite.jar version

**Comment by KaniskarK** [comment]
> > Now the Burp Pro Version is 2024.10.3 but the installed version ![image](https://private-user-images.githubusercontent.com/76870433/391316007-b62a28fb-6aaf-4664-b3d0-697b831a8210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTQzMDQsIm5iZiI6MTczMzA1NDAwNCwicGF0aCI6Ii83Njg3MDQzMy8zOTEzMTYwMDctYjYyYTI4ZmItNmFhZi00NjY0LWIzZDAtNjk3YjgzMWE4MjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDExNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZTRmYmM3NmJiMTBhZmE2OWIzMzEyNjJiZDljYTM1ODZhMjgyYTYyZGFkODg0ZDE1NzZiY2NhNDViYWNjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1luXPXyXzFLoFIs7Zn5SGrh79EMyKb5tdpO3DEqlzp8)
> > 
> > so how to upgarde to this version .
> 
> Burpsuite license version is always behind the current latest version of burpsuite.jar version 

Okay

**Comment by xiv3r** [comment]
> > > Now the Burp Pro Version is 2024.10.3 but the installed version ![image](https://private-user-images.githubusercontent.com/76870433/391316007-b62a28fb-6aaf-4664-b3d0-697b831a8210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTQzMDQsIm5iZiI6MTczMzA1NDAwNCwicGF0aCI6Ii83Njg3MDQzMy8zOTEzMTYwMDctYjYyYTI4ZmItNmFhZi00NjY0LWIzZDAtNjk3YjgzMWE4MjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDExNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZTRmYmM3NmJiMTBhZmE2OWIzMzEyNjJiZDljYTM1ODZhMjgyYTYyZGFkODg0ZDE1NzZiY2NhNDViYWNjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1luXPXyXzFLoFIs7Zn5SGrh79EMyKb5tdpO3DEqlzp8)
> > > so how to upgarde to this version .
> > 
> > 
> > Burpsuite license version is always behind the current latest version of burpsuite.jar version
> 
> Okay

Look for the README.md there's an update there

**Comment by KaniskarK** [comment]
> > > > Now the Burp Pro Version is 2024.10.3 but the installed version ![image](https://private-user-images.githubusercontent.com/76870433/391316007-b62a28fb-6aaf-4664-b3d0-697b831a8210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTQzMDQsIm5iZiI6MTczMzA1NDAwNCwicGF0aCI6Ii83Njg3MDQzMy8zOTEzMTYwMDctYjYyYTI4ZmItNmFhZi00NjY0LWIzZDAtNjk3YjgzMWE4MjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDExNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZTRmYmM3NmJiMTBhZmE2OWIzMzEyNjJiZDljYTM1ODZhMjgyYTYyZGFkODg0ZDE1NzZiY2NhNDViYWNjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1luXPXyXzFLoFIs7Zn5SGrh79EMyKb5tdpO3DEqlzp8)
> > > > so how to upgarde to this version .
> > > 
> > > 
> > > Burpsuite license version is always behind the current latest version of burpsuite.jar version
> > 
> > Okay
> 
> Look for the README.md there's an update there
> 

It automatically downgrading

**Comment by KaniskarK** [comment]
> I have solved the problem I download the latest version and install it, then load the burpsuite_pro.jar with the keygen


How can i contact you. Because i manually download the latest then only i ran keygen but it doenloaded the previous versions

**Comment by KaniskarK** [comment]
![image](https://github.com/user-attachments/assets/6f230468-432f-4c30-91aa-f57c71b91a72)

see i'm running the latest but it shows the previous version

**Comment by KaniskarK** [comment]
![image](https://github.com/user-attachments/assets/79f65fc6-0bfb-4b7c-88e6-a3257972157c)


i used this because when i click the activation it is loaded the previous ,once i cleared the license eveything now it is working

**Comment by KaniskarK** [comment]
Yes by clearing the license key. It is stored in some temp folder

**Comment by xiv3r** [comment]
Link are now updated 

From
```
https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar&version=&
```
To
```
https://portswigger-cdn.net/burp/releases/download?product=pro&version=&type=&
```

**Comment by KaniskarK** [comment]
👍🏻
