### ISSUE TITLE
Installing problem on windows

### ISSUE THREAD

**Issue by sodacream721** [xiv3r/Burpsuite-Professional#16]
Hi, failed to install on windows.
This is error text

Required JRE-8 is Installed
IdentifyingNumber : {71024AE4-039E-4CA4-87B4-2F64180431F0}
Name              : Java 8 Update 431 (64-bit)
Vendor            : Oracle Corporation
Version           : 8.0.4310.10
Caption           : Java 8 Update 431 (64-bit)

Burp Suite Professional JAR file is available.
Checking its Integrity ....
File Looks fine. Lets proceed for Execution

Burp.bat file is created

Burp-Suite-Pro.vbs file is created.
rm : Cannot find path 'C:\Windows\system32\Linux_setup.sh' because it does not exist.
At C:\Burp\install.ps1:63 char:1
+ rm Linux_setup.sh
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\system32\Linux_setup.sh:String) [Remove-Item], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

del : Cannot find path 'C:\Windows\system32\.github\' because it does not exist.
At C:\Burp\install.ps1:64 char:1
+ del -Recurse -Force .\.github\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\system32\.github\:String) [Remove-Item], ItemNotFoundExcepti
   on
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Reloading Environment Variables ....

Starting Keygenerator ....

Starting Burp Suite Professional
Error: Unable to access jarfile burpsuite_pro_v.jar

PS C:\Windows\system32>

Any idea how to fix this please
![Clipboard01](https://github.com/user-attachments/assets/da8a0255-54c2-4847-ae3b-93172ff59953)
?

**Comment by K1ngJok3r** [comment]
1. Open the `install.ps1` file in editor.
2. Delete the entire existing code and paste the following in the file:
```
# Set Wget Progress to Silent, Becuase it slows down Downloading by 50x
echo "Setting Wget Progress to Silent, Becuase it slows down Downloading by 50x`n"
$ProgressPreference = 'SilentlyContinue'

# Check JDK-21 Availability or Download JDK-21
$jdk19 = Get-WmiObject -Class Win32_Product -filter "Vendor='Oracle Corporation'" |where Caption -clike "Java(TM) SE Development Kit 21*"
if (!($jdk21)){
    echo "`t`tDownnloading Java JDK-21 ...."
    wget "https://download.oracle.com/java/21/archive/jdk-21_windows-x64_bin.exe" -O jdk-21.exe  
    echo "`n`t`tJDK-21 Downloaded, lets start the Installation process"
    start -wait jdk-21.exe
    rm jdk-21.exe
}else{
    echo "Required JDK-21 is Installed"
    $jdk21
}

# Check JRE-8 Availability or Download JRE-8
$jre8 = Get-WmiObject -Class Win32_Product -filter "Vendor='Oracle Corporation'" |where Caption -clike "Java 8 Update *"
if (!($jre8)){
    echo "`n`t`tDownloading Java JRE ...."
    wget "https://javadl.oracle.com/webapps/download/AutoDL?BundleId=247947_0ae14417abb444ebb02b9815e2103550" -O jre-8.exe
    echo "`n`t`tJRE-8 Downloaded, lets start the Installation process"
    start -wait jre-8.exe
    rm jre-8.exe
}else{
    echo "`n`nRequired JRE-8 is Installed`n"
    $jre8
}

# Downloading Burp Suite Professional
    echo "`n`t`tDownloading Latest Burp Suite Professional..."
    $version = "2024.11.1"
    Invoke-WebRequest -Uri "https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar&version=$version" -OutFile "burpsuite_pro_v$version.jar"
    echo "`nBurp Suite Professional is Downloaded.`n"

# Creating Burp.bat file with command for execution
if (Test-Path burp.bat) {rm burp.bat}
$path = "java --add-opens=java.desktop/javax.swing=ALL-UNNAMED--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -javaagent:`"$pwd\loader.jar`" -noverify -jar `"$pwd\burpsuite_pro_v$version.jar`""
$path | add-content -path Burp.bat
echo "`nBurp.bat file is created"


# Creating Burp-Suite-Pro.vbs File for background execution
if (Test-Path Burp-Suite-Pro.vbs) {
   Remove-Item Burp-Suite-Pro.vbs}
echo "Set WshShell = CreateObject(`"WScript.Shell`")" > Burp-Suite-Pro.vbs
add-content Burp-Suite-Pro.vbs "WshShell.Run chr(34) & `"$pwd\Burp.bat`" & Chr(34), 0"
add-content Burp-Suite-Pro.vbs "Set WshShell = Nothing"
echo "`nBurp-Suite-Pro.vbs file is created."

# Lets Activate Burp Suite Professional with keygenerator and Keyloader
echo "Reloading Environment Variables ...."
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
echo "`n`nStarting Keygenerator ...."
start-process java.exe -argumentlist "-jar loader.jar"
echo "`n`nStarting Burp Suite Professional"
java --add-opens=java.desktop/javax.swing=ALL-UNNAMED--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -javaagent:"loader.jar" -noverify -jar "burpsuite_pro_v$version.jar"
```
3. Run `install.ps1` file again. You might get some warnings.
4. Run the `.vbs` file and continue with the steps mentioned in the original documentation.

**Comment by sodacream721** [comment]
Many thanks for your help but new issues have come

IdentifyingNumber : {71024AE4-039E-4CA4-87B4-2F64180431F0}
Name              : Java 8 Update 431 (64-bit)
Vendor            : Oracle Corporation
Version           : 8.0.4310.10
Caption           : Java 8 Update 431 (64-bit)


                Downloading Latest Burp Suite Professional...

Burp Suite Professional is Downloaded.


Burp.bat file is created

Burp-Suite-Pro.vbs file is created.
Reloading Environment Variables ....


Starting Keygenerator ....


Starting Burp Suite Professional
Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Error opening zip file or JAR manifest missing : loader.jar
Error occurred during initialization of VM
agent library failed Agent_OnLoad: instrument


PS C:\Windows\system32>

**Comment by sodacream721** [comment]
Finally installation works fine but the burp doesn't accept this generated code.

**Comment by Rushaway** [comment]
Did you find a solution for the generated key not accepted ?

**Comment by sodacream721** [comment]
Yes, it’s described in issue 10.
