### ISSUE TITLE
icon not showing in kali 

### ISSUE THREAD

**Issue by jokerexe01** [xiv3r/Burpsuite-Professional#3]
when ever i opening the bursuite pro its not showing the icon in desk to dock also not in dash to panel. its shoing a gear icon not the burpsuite icon. i have tried many techniques to fix this but i failed. but its working in ubuntu. burpsuite is working totaly fine but i really need that icon. plz resolve this problem. 
![image](https://github.com/user-attachments/assets/91ae020d-c431-4878-98d1-656478a9d7e9)

**Comment by xiv3r** [comment]
> when ever i opening the bursuite pro its not showing the icon in desk to dock also not in dash to panel. its shoing a gear icon not the burpsuite icon. i have tried many techniques to fix this but i failed. but its working in ubuntu. burpsuite is working totaly fine but i really need that icon. plz resolve this problem. ![image](https://private-user-images.githubusercontent.com/146594936/368184343-91ae020d-c431-4878-98d1-656478a9d7e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTc1OTMsIm5iZiI6MTcyNjc5NzI5MywicGF0aCI6Ii8xNDY1OTQ5MzYvMzY4MTg0MzQzLTkxYWUwMjBkLWM0MzEtNDg3OC05OGQxLTY1NjQ3OGE5ZDdlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwMTU0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjQ1M2FlNWE0YmFhYTY5MTYwMWMyNTRmOGQwMjg1YTE1MjM3ODZkNGJkMjQ5ODdlMjJiNjU0YzVjMTVmM2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Co_ZHhDAX09O3GGk_A-QNlnbr4unCRoqzr2SX5L5ZzA)

did you try to create a launcher and select the burpsuite community icon?

**Comment by jokerexe01** [comment]
did you mean that .desktop file ?

**Comment by xiv3r** [comment]
> did you mean that .desktop file ?

if you can't find the icon kindly download the burpsuite community `apt install burpsuite` then proceed by creating the launcher for burpsuite pro using burpsuite community icon

**Comment by ghbfgb** [comment]
it is not opening what should i do next ?

**Comment by ghbfgb** [comment]
Unable to access jarfile burpsuite_pro_v.jar      this error is showing but i opened power shell as a adminstattor

**Comment by xiv3r** [comment]
> Unable to access jarfile burpsuite_pro_v.jar this error is showing but i opened power shell as a adminstattor

maybe this will help you

 https://t.me/burpsuite/429
